# Setup
title:               GSoC 2020
tagline:             'BeagleBoard.org'
description:         'This website is created for keeping track of the Development of "Cape compatibility layer for BeagleBone Black and BeagleBone AI" project.'
url:                 https://deepaklorkhatri.me
baseurl:             /GSoC2020_BeagleBoard.org
paginate:            5
paginate_path:       "/blog/page:num/"
permalink:           pretty

# About/contact
author:
  name:              Deepak Khatri
  url:               https://deepaklorkhatri.me/
  email:             deepaklorkhatri7@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-octicons

# Custom vars
version:             1.5
# week:                 12
status:              "Completed ✔️"
google_analytics_id: #UA-XXXX-Y
