# Setup
title:               GitHub Externship 2021
tagline:             'BeagleBoard.org'
description:         'This website is created for documenting my work done during the GitHub Externship for BeagleBoard.org.'
url:                 https://sheldor-abhi.github.io
baseurl:             /GitHub_Externship_2021
paginate:            5
paginate_path:       "/blog/page:num/"
permalink:           pretty

# About/contact
author:
  name:              Abhishek Shetty
  url:               https://sheldor-abhi.github.io/
  email:             shettyabhishek2020@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-octicons

# Custom vars
# version:             1.5
# week:                 12
status:              "Completed ✔️"
# google_analytics_id: #UA-XXXX-Y
